# Generated by Django 4.2.1 on 2023-05-14 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do tema')),
                ('description', tinymce.models.HTMLField()),
                ('path', models.CharField(max_length=50, verbose_name='Pasta do tema')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(blank=True, default='Página', max_length=50, verbose_name='Nome do link da página')),
                ('title', models.CharField(max_length=200, verbose_name='Título da página')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo da página')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('published', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Ordem da página')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
