# Generated by Django 4.2.1 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_theme_has_navbar_theme_has_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='has_header',
            field=models.BooleanField(blank=True, default=False, verbose_name='O tema mostra o header'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='has_navbar',
            field=models.BooleanField(blank=True, default=True, verbose_name='O tema mostra o navbar'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='has_sidebar',
            field=models.BooleanField(blank=True, default=False, verbose_name='O tema mostra o sidebar'),
        ),
    ]
