# Generated by Django 4.2.1 on 2023-05-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_theme_can_create_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='can_create_page',
            field=models.BooleanField(blank=True, default=True, verbose_name='O tema pode criar páginas'),
        ),
    ]
