# Generated by Django 4.2.1 on 2023-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_theme_can_create_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image_url',
            field=models.URLField(default='', max_length=255, verbose_name='Image do Tema'),
        ),
    ]
