# Generated by Django 4.2.1 on 2023-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogconfiguration',
            name='show_post_header',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='blogconfiguration',
            name='show_post_image',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
