# Generated by Django 4.2.1 on 2023-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do seu blog'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Usuário sem nome', max_length=200, verbose_name='Seu nome'),
        ),
    ]
